import './globals.css'
import ContextWrapper from '@/components/wrapper/contextWrapper'
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full">
			<ContextWrapper>
				<body className="h-full">{children}</body>
			</ContextWrapper>
			<Analytics/>
		</html>
	)
}
